previews:
  generation: automatic
  expireAfterDays: 3

services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      sudo apt-get update &&
      sudo apt-get install -y python3.10 python3.10-venv python3.10-dev &&
      python3.10 -m venv env &&
      source env/bin/activate &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: |
      source env/bin/activate &&
      python app.py --host=0.0.0.0 --port=$PORT
    envVars:
      - key: MY_ENV_VAR
        value: production-value  # Adjust as needed
      - key: ANOTHER_ENV_VAR
        value: another-value  # Adjust as needed

databases:
  - name: my_database
    databaseName: my_db
    user: my_user
    plan: standard
